name: raptor_test
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
    - einops
    - h5py
    - ipykernel
    - ipywidgets
    - jupyterlab
    - matplotlib
    - notebook
    - numpy
    - opencv-python
    - Overcomplete
    - pandas
    - pillow
    - python-dotenv
    - scikit-image
    - scikit-learn
    - scipy
    - seaborn
    - timm
    - torch==2.3.1
    - torchvision
    - tqdm
    - wandb
    - zarr